# This is a basic workflow to help you get started with Actions

name: Deploy to Firebase

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  deploy_to_firebase_hosting:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      
      - name: Deploy to Firebase
      - run: cd functions
      - run: npm install
      - run: npm install -g firebase-tools
      - run: npm run build
      - run: cd ..
      - run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
